name: Check java formatting

on:
  push:

  pull_request:
    branches: [ master ]

jobs:
  check_java_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Show all branch
        run: |
          git branch
          git branch -r

      - name: Download google-java-format 1.8
        run: |
          curl -L -o $HOME/google-java-format.jar https://github.com/google/google-java-format/releases/download/google-java-format-1.8/google-java-format-1.8-all-deps.jar
          curl -L -o $HOME/google-java-format-diff.py https://raw.githubusercontent.com/google/google-java-format/google-java-format-1.8/scripts/google-java-format-diff.py

      - name: Check Java formatting
        run: |
          diff=$(git diff -U0 $(git merge-base HEAD origin/master) | python $HOME/google-java-format-diff.py --google-java-format-jar=$HOME/google-java-format.jar -p1)
          if [[ $diff ]]; then
            echo "Please run google-java-format on the changes in this pull request"
            git diff -U0 $(git merge-base HEAD origin/master) | python $HOME/google-java-format-diff.py --google-java-format-jar=$HOME/google-java-format.jar -p1
            exit 1
          fi